Repository tryber/sd-010-a-project-recipes-app, pull requests merged in 2021-06, with the labels that each got.

#8 [Group 1] Feat: estruturação inicial
  package-lock.json
  src/App.js
  src/Pages/Drinks.js
  src/Pages/Foods.js
  src/Pages/Login.js
  src/components/Routes.js
  src/services/Data.js
  src/store/Context.js
  src/store/Provider.js
Labels: Group 1

#11 [Main group 22] - req 0
  README.md
  package-lock.json
  src/App.js
  src/components/BottomMenu.jsx
  src/components/Header.jsx
  src/components/Routes.js
  src/components/SearchBar.jsx
  src/contexts/RecipesContext.jsx
  src/contexts/RecipesProvider.jsx
  src/contexts/UserContext.jsx
  src/contexts/UserProvider.jsx
  src/pages/DoneRecipes.jsx
  src/pages/DrinksRecipes.jsx
  src/pages/ExploreDrinksIngredients.jsx
  src/pages/ExploreDrinksRecipes.jsx
  src/pages/ExploreFoodsIngredients.jsx
  src/pages/ExploreFoodsRecipes.jsx
  src/pages/ExploreOriginLocal.jsx
  src/pages/ExploreRecipes.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/FoodRecipes.jsx
  src/pages/Login.jsx
  src/pages/Perfil.jsx
  src/pages/ProgressDrinkRecipes.jsx
  src/pages/ProgressFoodRecipes.jsx
  src/pages/RecipesDrinkDetails.jsx
  src/pages/RecipesFoodDetails.jsx
  src/styles/DoneRecipes.css
  src/styles/DrinksRecipes.css
  src/styles/ExploreDrinksIngredients.css
  src/styles/ExploreDrinksRecipes.css
  src/styles/ExploreFoodsIngredients.css
  src/styles/ExploreFoodsRecipes.css
  src/styles/ExploreOriginLocal.css
  src/styles/ExploreRecipes.css
  src/styles/FavoriteRecipes.css
  src/styles/FoodRecipes.css
  src/styles/Login.css
  src/styles/Perfil.css
  src/styles/ProgressDrinkRecipes.css
  src/styles/ProgressFoodRecipes.css
  src/styles/RecipesDrinkDetails.css
  src/styles/RecipesFoodDetails.css
  src/styles/reset.css
  src/tests/DoneRecipes..test.js
  src/tests/DrinksRecipes.test.js
  src/tests/ExploreDrinksIngredients.test.js
  src/tests/ExploreDrinksRecipes.test.js
  src/tests/ExploreFoodsIngredients.test.js
  src/tests/ExploreFoodsRecipes.test.js
  src/tests/ExploreOriginLocal.test.js
  src/tests/ExploreRecipes.test.js
  src/tests/FavoriteRecipes.test.js
  src/tests/FoodRecipes.test.js
  src/tests/Login.test.js
  src/tests/Perfil.test.js
  src/tests/ProgressDrinkRecipes.test.js
  src/tests/ProgressFoodRecipes.test.js
  src/tests/RecipesDrinkDetails.test.js
  src/tests/RecipesFoodDetails.test.js
Labels: Group-22

#57 [Grupo 4] Requisito 0
  package-lock.json
  package.json
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Login.js
  src/pages/Bebidas.js
  src/pages/BebidasDetalhes.js
  src/pages/BebidasEmProcesso.js
  src/pages/Comidas.js
  src/pages/ComidasDetalhes.js
  src/pages/ComidasEmProcesso.js
  src/pages/Explorar.js
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarBebidasIngredientes.js
  src/pages/ExplorarComidas.js
  src/pages/ExplorarComidasArea.js
  src/pages/ExplorarComidasIngredientes.js
  src/pages/Ingredientes.js
  src/pages/Login.js
  src/pages/PaginaNaoEncontrada.js
  src/pages/Perfil.js
  src/pages/ReceitasFavoritas.js
  src/pages/ReceitasFeitas.js
  src/pages/Routes.js
  src/redux/actions/foodServiceAction.js
  src/redux/actions/userAction.js
  src/redux/reducers/foodReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/userReducer.js
  src/redux/store/index.js
  src/services/index.js
Labels: code-review

#18 [Group 14] Feat: Req-19
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/compenents/Footer.js
  src/contexts/FakeContext.js
  src/pages/Fakepage.js
  src/styles/Fakestyle.css
  src/styles/Footer.css
Labels: Group-14, code-review

#68 feat: Login screen
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/Routes.js
  src/context/Context.js
  src/context/Provider.js
  src/context/context.js
  src/pages/otherPages/Login.js
  src/pages/otherPages/login.js
  src/pages/recipes/recipesPage.js
Labels: group-19

#36 [Group 25] - Initial Project
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/components/shared/button/index.jsx
  src/components/shared/button/style.css
  src/components/shared/input/index.jsx
  src/components/shared/input/style.css
  src/context/userContext/userContext.js
  src/context/userContext/userProvider.js
  src/index.css
  src/index.js
  src/pages/NotFound/index.jsx
  src/styles/global.css
Labels: Group 25

#72 Login Page:
  src/App.js
  src/context/UserProvider.js
  src/pages/Login.js
  src/pages/Main.js
  src/tests/App.test.js
  src/tests/Login.test.js
Labels: code-review

#63 Requisito 19
  src/components/LowerMenu.js
Labels: code-review

#91 Requisito 20
  package-lock.json
  package.json
  src/components/LowerMenu.js
Labels: code-review

#24 [Grupo 14] Tela de Login
  src/App.js
  src/contexts/UserContext.js
  src/contexts/UserProvider.js
  src/pages/LoginPage.js
Labels: Group-14, code-review

#61 [GROUP-3] tela login
  src/App.css
  src/App.js
  src/pages/Login.js
  src/pages/index.js
  src/styles/login.js
Labels: inDevelopement

#65 [Group 1]Feat: requisito 2 ao 8
  src/Pages/Login.js
  src/store/Provider.js
Labels: Group 1

#107 [ Group 19 ] tests for Login screen
  src/App.css
  src/pages/otherPages/Login.js
  src/services/renderWithRouter.js
  src/tests/login.test.js
Labels: group-19

#87 [ Group 31 ] Header + fix Router
  src/App.js
  src/components/header/ProfileBtn.jsx
  src/components/header/SearchBtn.jsx
  src/components/header/index.js
  src/components/searchBar/index.js
  src/context/AppContext.jsx
  src/pages/DrinInProgress/index.js
  src/pages/Drink/index.js
  src/pages/DrinkDetails/index.js
  src/pages/Explore/index.js
  src/pages/ExploreDrinks/index.js
  src/pages/ExploreFoods/index.js
  src/pages/Food/index.js
  src/pages/FoodDetails/index.js
  src/pages/FoodInProgress/index.js
  src/pages/Login/index.js
Labels: code-review

#118 feat: requirement1
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/components/Footer.jsx
  src/components/Header.jsx
  src/pages/Login.js
  src/reducers/index.js
  src/store/index.js
Labels: code-review

#67 [Grupo 16] - Componente Header e Página de Perfil (Profile Page)
  package-lock.json
  package.json
  src/App.js
  src/components/Footer/Footer.jsx
  src/components/Generics/Button.jsx
  src/components/Generics/Input.jsx
  src/components/Header/Header.jsx
  src/components/Header/styles.js
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBarButton.jsx
  src/components/SearchBar/styles.js
  src/pages/Explore.jsx
  src/pages/Home.jsx
  src/pages/Profile.jsx
  src/styles/profile.js
Labels: code-review

#101 [Group 25] - Requirement 13
  src/App.js
  src/components/SearchBar/data.js
  src/components/SearchBar/index.jsx
  src/components/SearchBar/searchBar.test.js
  src/components/shared/input/index.jsx
  src/pages/Foods/index.jsx
Labels: Group 25, code-review

#115 first commit - rename archives for jsx
  src/App.css
  src/Pages/Drinks.jsx
  src/Pages/Explore/DrinkExplore.jsx
  src/Pages/Explore/DrinksIngredientsExplore.jsx
  src/Pages/Explore/Explore.jsx
  src/Pages/Explore/ExploreFoodSource.js
  src/Pages/Explore/ExploreFoodSource.jsx
  src/Pages/Explore/FoodExplore.jsx
  src/Pages/Explore/FoodIngredientsExplore.jsx
  src/Pages/FavoriteRecipes.jsx
  src/Pages/Foods.jsx
  src/Pages/Login.jsx
  src/Pages/Profile.jsx
  src/Pages/RecipesDone.jsx
  src/components/Footer.jsx
  src/components/Routes.jsx
  src/services/Data.jsx
  src/store/Context.jsx
  src/store/Provider.jsx
Labels: Group 1

#137 [Main group 12] req2
  src/Routes.js
  src/login/login.js
  src/pages/LoginPage/Login.js
Labels: code-review

#99 [Group 18] - Requisito 19 ao 24
  src/App.js
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/FormLogin/formLogin.css
  src/Components/FormLogin/index.jsx
  src/Pages/Details.jsx
  src/Pages/Explore.jsx
  src/Pages/ExploreArea.jsx
  src/Pages/ExploreByType.jsx
  src/Pages/ExploreIngredients.jsx
  src/Pages/InProcess.jsx
  src/Pages/ListofRecipes.jsx
  src/Pages/Login.jsx
  src/Pages/Profile.jsx
  src/Pages/RecipeMainPage.jsx
  src/Router.jsx
  src/tests/Footer.test.js
  src/tests/renderWithRoute.js
Labels: bug

#177 [Main group 22] - Recipes screen and Merge
  src/App.js
  src/components/Categories.jsx
  src/components/RecipesList.jsx
  src/components/Routes.js
  src/contexts/RecipesProvider.jsx
  src/helpers/endpoints.js
  src/hooks/useRecipesFilter.js
  src/index.js
  src/pages/DrinksRecipes.jsx
  src/pages/FoodRecipes.jsx
  src/pages/Recipes.jsx
  src/renderWithRouterAndProvider.js
  src/services/theMealAPI.js
  src/tests/BottomMenu.test.js
  src/tests/DrinksRecipes.test.js
  src/tests/ExploreDrinksIngredients.test.js
  src/tests/ExploreDrinksRecipes.test.js
  src/tests/ExploreFoodsIngredients.test.js
  src/tests/ExploreFoodsRecipes.test.js
  src/tests/ExploreOriginLocal.test.js
  src/tests/ExploreRecipes.test.js
  src/tests/FavoriteRecipes.test.js
  src/tests/FoodRecipes.test.js
  src/tests/Perfil.test.js
  src/tests/ProgressDrinkRecipes.test.js
  src/tests/ProgressFoodRecipes.test.js
  src/tests/RecipesDrinkDetails.test.js
  src/tests/RecipesFoodDetails.test.js
  src/tests/mocks/recipesPageData.js
  src/tests/recipesPage.test.js
Labels: Group-22

#195 Requisito 21
  src/App.js
  src/Pages/Explore.js
  src/Pages/MainRecipes.js
  src/components/LowerMenu.js
Labels: code-review

#182 Todas Rotas criadas, links para navegação não criados
  src/App.js
  src/components/Header.jsx
  src/pages/DrinkDetail.jsx
  src/pages/DrinkDetailProgress.jsx
  src/pages/Drinks.jsx
  src/pages/Explorer.jsx
  src/pages/ExplorerDrink.jsx
  src/pages/ExplorerDrinkIngredients.jsx
  src/pages/ExplorerRecipe.jsx
  src/pages/ExplorerRecipeArea.jsx
  src/pages/ExplorerRecipeIngredients.jsx
  src/pages/Profile.jsx
  src/pages/RecipeDetail.jsx
  src/pages/RecipeDetailProgress.jsx
  src/pages/RecipeDone.jsx
  src/pages/RecipeFavorite.jsx
  src/pages/Recipes.jsx
Labels: Group 7
