Repository tryber/sd-010-a-project-recipes-app, pull requests merged in 2021-07, with the labels that each got.

#226 [Group 11] [Requirements: 16, 17 and 18]
  src/App.css
  src/components/CocktailsCards.jsx
  src/components/MealsCards.jsx
  src/components/SearchBar.jsx
  src/components/SearchButton.jsx
  src/context/CocktailsProvider.js
  src/context/MealsProvider.js
  src/pages/Cocktails.js
  src/pages/MainCocktails.jsx
  src/pages/MainRecipes.jsx
Labels: code-review

#188 Main group 14 footer tests
  src/App.js
  src/App.test.js
  src/compenents/Footer.js
  src/compenents/Header.js
  src/compenents/MainRecepies.js
  src/compenents/RecipeCard.js
  src/contexts/SeachbarProvider.js
  src/contexts/SearchbarContext.js
  src/services/fetchApi.js
  src/tests/Footer.spec.js
  src/tests/Login.test.js
  src/tests/renderWithRouter.js
Labels: Group-14, code-review

#237 :sparkles: Requisito 22
  src/App.js
  src/components/LowerMenu.js
  src/configs/configs.js
  src/contexts/app/AppContext.js
  src/contexts/app/AppProvider.js
  src/contexts/drinks/DrinksProvider.js
  src/index.js
Labels: code-review

#241 :sparkles: Requisito 23
  src/components/LowerMenu.js
Labels: code-review

#172 [Group 25] - Requirement 19
  src/App.js
  src/components/footer/Footer.js
  src/components/footer/Footer.spec.js
  src/pages/Foods/index.js
Labels: Group 25, code-review

#218 [Group 1] Feat: requisito 25 a 27 e 32
  src/Pages/Drinks.jsx
  src/Pages/Foods.jsx
  src/services/Data.jsx
  src/store/Provider.jsx
Labels: Group 1

#163 Req11 header group 25
  src/App.js
  src/components/header/header.test.js
  src/components/header/index.jsx
  src/components/searchBar/SearchBar.jsx
  src/components/searchButton/index.jsx
  src/pages/Drinks/index.jsx
  src/pages/Foods/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/Perfil/index.jsx
Labels: Group 25

#170 [Group 25] - Footer Menu
  .gitignore
  cypress/plugins/index.js
  cypress/support/index.js
  package-lock.json
  src/App.js
  src/components/footer/Data.js
  src/components/footer/Footer.spec.js
  src/components/footer/index.js
  src/components/shared/link/index.jsx
  src/images/drinkIcon.svg
  src/images/exploreIcon.svg
  src/images/mealIcon.svg
  src/pages/Drinks/index.js
  src/pages/Explorer/index.js
  src/pages/ExplorerDrinks/index.js
  src/pages/ExplorerDrinksIngredients/index.js
  src/pages/ExplorerFoods/index.js
  src/pages/ExplorerFoodsIngredients/index.js
  src/pages/ExplorerFoodsLocal/index.js
  src/pages/Foods/index.js
  src/pages/Perfil/index.js
  src/styles/global.css
Labels: Group 25, code-review

#213 [Grupo 4] Página de Comidas e Página de Bebidas
  src/components/DrinksCards.js
  src/components/DrinksCategoryButtons.js
  src/components/Loading.js
  src/components/MealsCards.js
  src/components/MealsCategoryButtons.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/ReceitasFeitas.js
  src/redux/actions/drinksAction.js
  src/redux/actions/mealsAction.js
  src/redux/reducers/drinksReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/mealsReducer.js
  src/services/drinks.js
  src/services/index.js
  src/services/meals.js
Labels: Group 4, code-review

#185 [Grupo 4] req 2 3 4 5
  src/pages/Login.js
  src/redux/actions/userAction.js
  src/redux/reducers/index.js
  src/redux/reducers/userReducer.js
Labels: Group 4, code-review

#214 [Grupo 4] Menu inferior
  src/components/Footer.js
  src/footer.module.css
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/Explorar.js
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarBebidasIngredientes.js
  src/pages/ExplorarComidas.js
  src/pages/ExplorarComidasArea.js
  src/pages/ExplorarComidasIngredientes.js
  src/pages/Perfil.js
Labels: Group 4, code-review

#151 [Grupo 4] componente header, requisitos 9 ao 12
  package-lock.json
  src/components/BarraBuscar.js
  src/components/Header.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/Explorar.js
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarBebidasIngredientes.js
  src/pages/ExplorarComidas.js
  src/pages/ExplorarComidasArea.js
  src/pages/ExplorarComidasIngredientes.js
  src/pages/Perfil.js
  src/pages/ReceitasFavoritas.js
  src/pages/ReceitasFeitas.js
Labels: Group 4, code-review

#143 [Group 25] Requisito 2, 3 e 4
  src/App.js
  src/components/LoginForm/data.js
  src/components/LoginForm/index.jsx
  src/pages/Login/index.jsx
Labels: Group 25, code-review

#271 [Group 25] - Requeriment 18
  src/components/CardRecipe/index.jsx
  src/components/SearchBar/index.jsx
  src/context/recipesContext/recipesProvider.js
  src/utils/functions.js
Labels: Group 25

#265 [Group 25] - Requeriment 17
  src/components/CardRecipe/index.jsx
  src/components/SearchBar/index.jsx
  src/context/recipesContext/recipesProvider.js
Labels: Group 25

#283 [Group 25] - Requeriment 82/84
  src/App.js
  src/components/shared/input/index.jsx
  src/pages/Drinks/index.js
  src/pages/Drinks/index.jsx
  src/pages/Foods/index.js
  src/pages/Foods/index.jsx
  src/pages/Perfil/index.js
  src/pages/Perfil/index.jsx
Labels: Group 25

#284 [Group 25] - Requeriment 83
  src/pages/Perfil/index.jsx
Labels: Group 25

#287 [Group 25] - Requeriment 85/86/87
  src/pages/Perfil/index.jsx
Labels: Group 25

#281 [Group 1] Feat: requisito do 28 ao 31
  src/Pages/Drinks.jsx
  src/Pages/Foods.jsx
  src/Pages/Profile.jsx
  src/services/Data.jsx
  src/store/Provider.jsx
Labels: Group 1

#245 Requisito 24
  src/components/LowerMenu.js
Labels: code-review

#122 [Group 25] Login Page
  package-lock.json
  src/App.js
  src/components/LoginForm/LoginForm.test.js
  src/components/LoginForm/data.js
  src/components/LoginForm/index.jsx
  src/components/shared/button/index.jsx
  src/components/shared/input/index.jsx
  src/pages/Login/index.jsx
  src/tests/renderWithRouter.js
  src/utils/setLocalStorage.js
  src/utils/validations.js
Labels: Group 25, inDevelopement

#314 [Group 11][adapts header test to use context and modifies description of searchbar tests]
  src/components/CocktailsCards.jsx
  src/components/MealsCards.jsx
  src/components/SearchBar.jsx
  src/components/SearchButton.jsx
  src/context/MealsProvider.js
  src/context/UserProvider.js
  src/pages/MainCocktails.jsx
  src/pages/MainRecipes.jsx
  src/tests/Header.test.js
  src/tests/SearchBar.test.js
  src/tests/mock/mockMealAPI.js
Labels: code-review

#311 [Group 1]Feat: tela de explorar
  src/Pages/Explore/Explore.jsx
Labels: Group 1

#322 [Group 1] Feat: requisito do 82 ao 87
  src/Pages/Profile.jsx
Labels: Group 1

#330 [Group 25] - Requeriment 60
  package-lock.json
  src/App.js
  src/components/CardRecipeFavorite/index.jsx
  src/components/LoginForm/LoginForm.test.js
  src/components/LoginForm/data.js
  src/components/LoginForm/index.jsx
  src/pages/Login/index.jsx
  src/pages/RecipesFavorite/index.jsx
  src/service/recipesApi.js
  src/tests/renderWithRouter.js
  src/utils/setLocalStorage.js
  src/utils/validations.js
Labels: Group 25

#332 [Group 25] - Requiment 60
  package-lock.json
  src/App.js
  src/components/CardRecipeFavorite/index.jsx
  src/components/LoginForm/LoginForm.test.js
  src/components/LoginForm/data.js
  src/components/LoginForm/index.jsx
  src/pages/Login/index.jsx
  src/pages/RecipesFavorite/index.jsx
  src/service/recipesApi.js
  src/tests/renderWithRouter.js
  src/utils/setLocalStorage.js
  src/utils/validations.js
Labels: Group 25

#324 [Group 11] [Explore Page - reqs 67, 68 and 69]
  src/components/CocktailsCards.jsx
  src/components/MealsCards.jsx
  src/context/CocktailsProvider.js
  src/context/MealsProvider.js
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreFood.jsx
  src/services/theMealAPI.js
  src/tests/Explore.test.js
  src/tests/ExploreDrinks.test.js
  src/tests/ExploreFood.test.js
  src/tests/SearchBar.test.js
Labels: code-review

#321 DetailsRecipe [ 34 - 46 ]
  cypress/integration/recipe_detail_spec.js
  src/App.css
  src/App.js
  src/components/DetailsRecipe/CardRecommendeds.js
  src/components/DetailsRecipe/FavoriteButton.js
  src/components/DetailsRecipe/HeaderPhoto.js
  src/components/DetailsRecipe/Ingredients.js
  src/components/DetailsRecipe/RecommendedRecipes.js
  src/components/DetailsRecipe/ShareButton.js
  src/components/DetailsRecipe/StartRecipeButton.js
  src/components/DetailsRecipe/TextInstructions.js
  src/components/DetailsRecipe/TextSubtitle.js
  src/components/DetailsRecipe/TitleRecipe.js
  src/components/DetailsRecipe/VideRecipe.js
  src/components/LowerMenu.js
  src/pages/DetailsRecipe.js
  src/pages/Explore.js
  src/pages/Home.js
  src/pages/MainRecipes.js
  src/pages/Perfil.js
Labels: code-review

#347 [Grupo 1] SearchBar - Requisitos 13 ao 18
  package-lock.json
  package.json
  src/App.css
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/index.js
  src/services/Data.jsx
  src/store/Provider.jsx
Labels: Group 1, code-review

#167 [Grupo 16] - Componente SearchBar (requisitos 14 a 18 - concluída)
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Card/Card.jsx
  src/components/Card/styles.js
  src/components/CardList/CardList.jsx
  src/components/CardList/styles.js
  src/components/Footer/styles.js
  src/components/MealVideo/MealVideo.jsx
  src/components/RecipeInfo/RecipeInfo.jsx
  src/components/RecipeIngredients/RecipeIngredients.jsx
  src/components/SearchBar/ResetSearchBarFiltersButton.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/styles.js
  src/context/FilteredRecipesContext.jsx
  src/hooks/useFilteredRecipes.js
  src/index.js
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/pages/RecipeDetails.jsx
  src/services/fetchFilteredRecipes.js
  src/styles/home.js
  src/styles/login.js
  src/styles/profile.js
Labels: code-review

#371 [Group 25] - Requeriment 61
  src/components/CardRecipeFavorite/index.jsx
  src/images/shareIcon.svg
  src/pages/RecipesFavorite/index.jsx
Labels: Group 25

#354 [Group 1] Sugestão de organização das pages
  package-lock.json
  src/Pages/Drinks/DrinkId.jsx
  src/Pages/Drinks/Drinks.jsx
  src/Pages/Explore/DrinkExplore.jsx
  src/Pages/Explore/Explore.jsx
  src/Pages/Explore/ExploreDrinks/DrinkExplore.jsx
  src/Pages/Explore/ExploreDrinks/DrinksIngredientsExplore.jsx
  src/Pages/Explore/ExploreFoods/ExploreFoodSource.jsx
  src/Pages/Explore/ExploreFoods/FoodExplore.jsx
  src/Pages/Explore/ExploreFoods/FoodIngredientsExplore.jsx
  src/Pages/Explore/FoodExplore.jsx
  src/Pages/Explore/NotFound.jsx
  src/Pages/Foods/FoodId.jsx
  src/Pages/Foods/Foods.jsx
  src/Pages/Profile/FavoriteRecipes.jsx
  src/Pages/Profile/Login.jsx
  src/Pages/Profile/Profile.jsx
  src/Pages/Profile/RecipesDone.jsx
  src/Pages/index.js
  src/components/ButtonExplore.jsx
  src/components/Routes.jsx
Labels: suggestion

#339 [Group 26] Styles
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/Cards.js
  src/components/FilterButtons.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Search.js
  src/images/background-login.jpg
  src/images/logo-recipies.svg
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/DoneRecipies.js
  src/pages/Explorar.js
  src/pages/FavoriteRecipies.js
  src/pages/Login.js
  src/pages/Perfil.js
  src/pages/drinks/DrinkDetails.js
  src/pages/drinks/DrinkProgress.js
  src/pages/explore/DrinkIngredients.js
  src/pages/explore/ExploreDrink.js
  src/pages/explore/ExploreFood.js
  src/pages/explore/FoodArea.js
  src/pages/explore/FoodIngredients.js
  src/pages/foods/FoodDetails.js
  src/pages/foods/FoodProgress.js
  src/styles/Cards.module.scss
  src/styles/Explore.module.scss
  src/styles/FilterButtons.module.scss
  src/styles/Footer.module.scss
  src/styles/Header.module.scss
  src/styles/Login.module.scss
  src/styles/MainPages.module.scss
  src/styles/Search.module.scss
Labels: Group 26, code-review

#125 Feature-header-group25
  package.json
  src/App.js
  src/components/header/header.test.js
  src/components/header/index.jsx
  src/components/itemCard/index.jsx
  src/components/searchBar/SearchBar.jsx
  src/components/searchButton/index.jsx
  src/context/drinkContext/drinkContext.js
  src/context/drinkContext/drinkProvider.js
  src/context/foodContext/foodContext.js
  src/context/foodContext/foodProvider.js
  src/pages/Drinks/index.js
  src/pages/Drinks/index.jsx
  src/pages/Foods/index.js
  src/pages/Foods/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/Perfil/index.js
  src/pages/Perfil/index.jsx
  src/test/functions.js
Labels: Group 25

#376 [Grupo 14] Tela de explorar
  src/App.js
  src/Login.test.js
  src/pages/Drinks.js
  src/pages/Explore.js
  src/pages/Foods.js
Labels: Group-14

#264 [GROUP-3] - main screen
  src/components/Buttons.jsx
  src/components/Categorias.jsx
  src/components/Header.js
  src/components/search bar/SearchBarForm.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/Explorar.js
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarBebidasING.js
  src/pages/ExplorarComidas.js
  src/pages/ExplorarComidasArea.js
  src/pages/ExplorarComidasING.js
  src/provider/ProviderBebida.js
  src/provider/ProviderComidas.js
  src/services/apisCategories.js
  src/services/apisMealsAndCocktails.js
  src/styles/header.js
Labels: inDevelopement

#100 [Group 25] - Barra de busca
  src/App.js
  src/components/CardRecipe/index.jsx
  src/components/SearchBar/data.js
  src/components/SearchBar/index.jsx
  src/components/SearchBar/mock.js
  src/components/SearchBar/searchBar.test.js
  src/components/header/index.jsx
  src/components/shared/button/index.jsx
  src/components/shared/input/index.jsx
  src/context/drinkContext/drinkContext.js
  src/context/drinkContext/drinkProvider.js
  src/context/foodContext/foodContext.js
  src/context/foodContext/foodProvider.js
  src/context/recipesContext/recipesContext.js
  src/context/recipesContext/recipesProvider.js
  src/pages/Details/index.jsx
  src/pages/Drinks/index.jsx
  src/pages/Foods/index.jsx
  src/service/recipesApi.js
  src/utils/functions.js
Labels: Group 25, inDevelopement

#278 [Group 25] - Perfil
  src/App.js
  src/components/CardRecipeFavorite/index.jsx
  src/components/shared/input/index.jsx
  src/pages/Perfil/index.jsx
  src/pages/RecipesFavorite/index.jsx
  src/service/recipesApi.js
Labels: Group 25, inDevelopement

#373 [GRUPO 18] Feat:Req 67-69
  src/Components/ExploreButtons/ExploreButtons.css
  src/Components/ExploreButtons/index.jsx
  src/Pages/Explore/index.jsx
  src/tests/Explore.test.js
Labels: code-review

#334 [Group 9] Requisitos: 13 a 18
  src/App.js
  src/components/RecipeCard.js
  src/components/Routes.js
  src/components/SearchBar.js
  src/context/RecipesContext.js
  src/context/RecipesProvider.js
  src/pages/RecipesDrinks.js
  src/pages/RecipesFoods.js
  src/services/api.js
  src/utils/searchBarInputsContent.js
Labels: code-review

#407 [Group 25] - Requeriment 62, 63
  src/components/CardRecipeFavorite/index.jsx
  src/pages/RecipesFavorite/index.jsx
Labels: Group 25

#410 [Group 25] - Requemirent 64
  src/components/CardRecipeFavorite/index.jsx
  src/pages/RecipesFavorite/index.jsx
Labels: Group 25

#416 [Group 25] - Requeriment 66
  src/components/CardRecipeFavorite/index.jsx
Labels: Group 25

#412 [Group19] Profile/screen
  src/App.css
  src/Routes.js
  src/components/Header.js
  src/components/RecipeList.css
  src/components/RecipesList.jsx
  src/context/Provider.js
  src/pages/Profile/Profile.js
  src/pages/otherPages/Login.js
  src/pages/recipes/DrinksDetails.js
  src/pages/recipes/Foods.js
  src/pages/recipes/MealDetails.js
  src/services/getDrinks.js
  src/services/getMeals.js
  src/services/localStorage.js
Labels: group-19

#274 [Grupo 4] resolvendo problema no merge
  package.json
  src/pages/ExplorarBebidasIngredientes.js
Labels: Group 4, code-review

#396 [ Grupo 4 ] req 6 , 7 e 8
  src/pages/ExplorarBebidasIngredientes.js
  src/pages/Login.js
  src/redux/reducers/index.js
  src/redux/reducers/user.js
Labels: Group 4, code-review

#432 [Group 1] Feat: requisitos 33, 34, 36, 39, 41, 42
  src/Pages/Drinks/DrinkId.jsx
  src/Pages/Drinks/DrinkInProgress.jsx
  src/Pages/Foods/FoodId.jsx
  src/Pages/Foods/FoodInProgress.jsx
  src/Pages/index.js
  src/components/Routes.jsx
  src/services/Data.jsx
Labels: Group 1

#356 [Main group 22] recipes test
  src/pages/Recipes.jsx
  src/tests/Login.test.js
  src/tests/mocks/recipesPageData.js
  src/tests/recipesPage.test.js
Labels: Group-22

#319 [Grupo 4] Barra de Busca
  src/components/BarraBuscar.js
  src/components/DrinksCards.js
  src/components/Header.js
  src/components/MealsCards.js
  src/components/SearchBar.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/redux/actions/drinksAction.js
  src/redux/actions/foodServiceAction.js
  src/redux/actions/loadingAction.js
  src/redux/actions/mealsAction.js
  src/redux/reducers/drinksReducer.js
  src/redux/reducers/foodReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/loadingReducer.js
  src/redux/reducers/mealsReducer.js
  src/services/drinks.js
  src/services/meals.js
Labels: Group 4, code-review

#443 [Group 1]Feat: tela de explorar por ingredientes - requisitos 75 ao 77
  src/Pages/Drinks/Drinks.jsx
  src/Pages/Explore/Explore.jsx
  src/Pages/Explore/ExploreDrinks/DrinkExplore.jsx
  src/Pages/Explore/ExploreDrinks/DrinksIngredientsExplore.jsx
  src/Pages/Explore/ExploreDrinks/ExploreDrinksIngredients.jsx
  src/Pages/Explore/ExploreFoods/ExploreArea.jsx
  src/Pages/Explore/ExploreFoods/ExploreFoodIngredients.jsx
  src/Pages/Explore/ExploreFoods/FoodExplore.jsx
  src/Pages/Explore/ExploreFoods/FoodIngredientsExplore.jsx
  src/Pages/Foods/Foods.jsx
  src/Pages/Profile/FavoriteRecipes.jsx
  src/Pages/Profile/Profile.jsx
  src/Pages/Profile/RecipesDone.jsx
  src/Pages/index.js
  src/components/ExploreButton.jsx
  src/components/IngredientsDrinkCard.jsx
  src/components/IngredientsFoodCard.jsx
  src/components/Routes.jsx
  src/components/index.js
  src/services/Data.jsx
  src/store/Provider.jsx
Labels: Group 1, inDevelopement

#457 [Group 11] [feat: implements requirements 44, 45 and 46]
  src/components/FavoriteButton.jsx
  src/context/MealsProvider.js
  src/effects/RecipeFav.js
  src/pages/DrinkDetails.jsx
  src/pages/FoodDetails.jsx
Labels: code-review

#433 [Group 25] - Requirements 33, 34, 36 e 42
  package-lock.json
  package.json
  src/App.jsx
  src/components/footer/index.jsx
  src/pages/Drink/index.jsx
  src/pages/Drinks/index.jsx
  src/pages/Explorer/index.jsx
  src/pages/ExplorerDrinks/index.jsx
  src/pages/ExplorerDrinksIngredients/index.jsx
  src/pages/ExplorerFoods/index.jsx
  src/pages/ExplorerFoodsIngredients/index.jsx
  src/pages/ExplorerFoodsLocal/index.jsx
  src/pages/Food/index.jsx
  src/pages/Foods/index.jsx
  src/pages/Perfil/index.jsx
  src/service/recipesApi.js
Labels: Group 25, code-review

#289 [Group 25] - Receitas Favoritas
  src/components/CardRecipeFavorite/index.jsx
  src/images/shareIcon.svg
  src/pages/RecipesFavorite/index.jsx
Labels: Group 25, code-review

#367 [Grupo 16] Tela Principal de Receitas - Filtragem por categorias
  src/components/CardList/CardList.jsx
  src/components/CategoriesList/CategoriesList.jsx
  src/context/RecipesContext.jsx
  src/effects/useFetchRecipes.js
  src/pages/Home.jsx
Labels: code-review

#466 [Group 25] - Requirements 35
  src/pages/Drink/index.jsx
  src/pages/Food/index.jsx
Labels: Group 25

#467 [ Grupo 4 ] Refatoração da função para criação da lista de ingredientes
  src/components/Recipe.js
  src/components/Recipe/Carousel.js
  src/components/Recipe/CarouselCard.js
  src/components/Recipe/Category.js
  src/components/Recipe/FavoriteDrink.js
  src/components/Recipe/FavoriteMeal.js
  src/components/Recipe/Image.js
  src/components/Recipe/Ingredients.js
  src/components/Recipe/Instructions.js
  src/components/Recipe/Recomendations.js
  src/components/Recipe/Share.js
  src/components/Recipe/Start.js
  src/components/Recipe/Title.js
  src/components/Recipe/Video.js
  src/pages/BebidasDetalhes.js
  src/pages/Comidas.js
  src/pages/ComidasDetalhes.js
  src/redux/actions/drinksAction.js
  src/redux/actions/mealsAction.js
  src/redux/reducers/drinksReducer.js
  src/redux/reducers/loadingReducer.js
  src/redux/reducers/mealsReducer.js
  src/services/drinks.js
  src/services/meals.js
  src/services/youtube.js
  src/styles/carousel.css
  src/styles/carouselCard.css
  src/styles/recipe.css
  src/utils/index.js
Labels: Group 4, code-review

#465 [Explore Page] - req-67-68-69
  src/pages/Explorar.js
Labels: Group 4, code-review

#464 [GROUP 18] feat: req 70-74
  src/Components/ExploreDrink/index.jsx
  src/Components/ExploreFood/index.jsx
  src/Pages/ExploreDrink/index.jsx
  src/Pages/ExploreFood/index.jsx
  src/Router.jsx
  src/services/fetchRecipes.js
Labels: code-review

#472 [Group 25] - Requirements 37
  package-lock.json
  package.json
  src/App.jsx
  src/pages/Drink/index.jsx
  src/pages/Food/index.jsx
Labels: Group 25

#475 [Group 25] - Requirement 38
  src/pages/Drink/index.jsx
  src/pages/Food/index.jsx
  src/styles/global.css
Labels: Group 25

#481 [Group 25] Req-27-RecipesList
  src/App.js
  src/context/foodContext/foodProvider.js
  src/context/recipesContext/recipesProvider.js
  src/pages/Drinks/index.jsx
  src/pages/Foods/index.jsx
Labels: Group 25

#482 [Group 25] - Requirements 41
  src/App.jsx
  src/components/shared/button/index.jsx
  src/pages/Drink/index.jsx
  src/pages/Food/index.jsx
Labels: Group 25

#484 [GROUP-3] - tela explorar ingredientes
  src/components/Card.jsx
  src/components/Categorias.jsx
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/ExplorarBebidasING.js
  src/pages/ExplorarComidasING.js
  src/provider/ProviderBebida.js
  src/provider/ProviderComidas.js
  src/services/fetchApiSearch.js
  src/services/fetchApisIngredients.js
Labels: inDevelopement

#486 [Group 25] - Requirements 43
  src/components/shared/button/index.jsx
  src/pages/Drink/index.jsx
  src/pages/Food/index.jsx
  src/styles/global.css
Labels: Group 25

#497 [Main group 22] recipe in progress
  src/components/IngredientsList.jsx
  src/components/RecipeDetailsHeader.jsx
  src/components/Routes.js
  src/contexts/RecipesProvider.jsx
  src/helpers/endpoints.js
  src/hooks/useIngredients.js
  src/hooks/useLocalStorage.js
  src/images/blackHeartIcon.svg
  src/images/drinkIcon.svg
  src/images/exploreIcon.svg
  src/images/mealIcon.svg
  src/images/searchIcon.svg
  src/images/shareIcon.svg
  src/images/whiteHeartIcon.svg
  src/index.css
  src/index.js
  src/pages/ProgressDrinkRecipes.jsx
  src/pages/ProgressFoodRecipes.jsx
  src/pages/RecipeInProgress.jsx
  src/pages/Recipes.jsx
  src/services/theMealAPI.js
  src/styles/BottomMenu.css
  src/styles/Global.css
  src/styles/IngredientsList.css
  src/styles/recipeDetailsHeader.css
  src/tests/mocks/recipeDetailsData.js
  src/tests/recipeDetailsInProgress.test.js
Labels: Group-22

#514 [Group 15] - Tela de Receita em Progresso
  src/helper/mealsOrDrinksMethods.js
  src/hooks/useClipboard.js
  src/hooks/useRecipeDetails.js
  src/hooks/useRecipeProgress.js
  src/pages/DrinkProgress.jsx
  src/pages/FoodProgress.jsx
Labels: Group-15

#516 [Grupo 15] - Recipes Done
  package-lock.json
  package.json
  src/components/RecipeDoneCard.jsx
  src/hooks/useClipboard.js
  src/hooks/useRecipeDetails.js
  src/hooks/useRecipeFilter.js
  src/hooks/useRecipeProgress.js
  src/pages/DrinkProgress.jsx
  src/pages/FoodProgress.jsx
  src/pages/RecipesDone.jsx
Labels: Group-15

#535 [Group 25] - Requeriment 67
  src/pages/Explorer/index.jsx
Labels: Group 25

#536 [Group 25] - Requeriment 68
  src/pages/Explorer/index.jsx
Labels: Group 25

#537 [Group 25] - Requeiment 69
  src/pages/Explorer/index.jsx
Labels: Group 25

#477 [Group 1] Fix: requisito 32
  src/Pages/Drinks/DrinkId.jsx
  src/Pages/Foods/FoodId.jsx
  src/services/Data.jsx
Labels: Group 1

#529 [ Main group 4 ] explore food or drinks
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarComidas.js
Labels: Group 4, code-review

#459 [Grupo 14] Testes da pagina de explorar
  src/pages/LoginPage.js
  src/tests/Explore.test.js
Labels: Group-14

#462 [Grupo 14] Testes da tela de explorar comidas e bebidas
  src/tests/ExploreFoodsDrinks.test.js
Labels: Group-14

#71 [Grupo 14] Feat: Req-9 e Req-12
  README.md
  package-lock.json
  src/App.js
  src/App.test.js
  src/compenents/Header.js
  src/compenents/SearchBar.js
  src/contexts/HeaderContext.js
  src/contexts/HeaderProvider.js
  src/contexts/RecipesAppContext.js
  src/pages/Perfil.js
  src/pages/ProfilePage.js
  src/pages/ReceitasFavoritas.js
  src/pages/ReceitasFeitas.js
  src/styles/Header.css
  src/styles/ProfilePage.css
  src/tests/Header.test.js
  src/tests/Login.test.js
  src/tests/Profile.test.js
Labels: Group-14

#518 [Group 25] Receitas Feitas
  src/components/ButtonsRecipesMade/data.js
  src/components/ButtonsRecipesMade/index.jsx
  src/components/ButtonsRecipesMade/style.css
  src/components/CardRecipesMade/index.jsx
  src/components/CardRecipesMade/style.css
  src/components/Footer/Data.js
  src/components/Footer/Footer.spec.js
  src/components/Footer/index.js
  src/components/Header/header.test.js
  src/components/Header/index.jsx
  src/components/ItemCard/index.jsx
  src/components/LoginForm/LoginForm.test.js
  src/components/SearchBar/searchBar.test.js
  src/components/footer/Footer.spec.js
  src/pages/Drinks/index.jsx
  src/pages/Explorer/index.jsx
  src/pages/ExplorerDrinks/index.jsx
  src/pages/ExplorerDrinksIngredients/index.jsx
  src/pages/ExplorerFoods/index.jsx
  src/pages/ExplorerFoodsIngredients/index.jsx
  src/pages/ExplorerFoodsLocal/index.jsx
  src/pages/Foods/index.jsx
  src/pages/Perfil/index.jsx
  src/pages/RecipesDone/index.jsx
  src/pages/RecipesDone/mockLocalStorage.js
  src/pages/RecipesDone/style.css
  src/pages/RecipesFavorite/index.jsx
Labels: Group 25, code-review

#527 [Group 25] - Tela e Explorar
  src/pages/Explorer/index.jsx
Labels: Group 25, code-review

#563 [Group 25] - Requeriment 75
  src/pages/ExplorerDrinksIngredients/index.jsx
  src/pages/ExplorerFoodsIngredients/index.jsx
  src/utils/functions.js
Labels: Group 25

#565 [Group 25] - Requeriment 76
  src/pages/ExplorerDrinksIngredients/index.jsx
  src/pages/ExplorerFoodsIngredients/index.jsx
  src/utils/functions.js
Labels: Group 25

#557 [Group 25] - Tela de explorar ingredientes
  src/components/Header/header.test.js
  src/components/SearchBar/searchBar.test.js
  src/pages/Explorer/index.jsx
  src/pages/ExplorerDrinksIngredients/index.jsx
  src/pages/ExplorerFoodsIngredients/index.jsx
  src/utils/functions.js
Labels: Group 25, inDevelopement

#530 [Grupo 16] Tela de Receitas Favoritas
  src/App.js
  src/components/FavoriteRecipeCard/FavoriteRecipeCard.jsx
  src/pages/FavoriteRecipes.jsx
Labels: code-review

#575 [Main group 14] Integrate components
  src/App.css
  src/App.js
  src/App.test.js
  src/compenents/DrinkCards.js
  src/compenents/FilterButtons.js
  src/compenents/Footer.js
  src/compenents/Header.js
  src/compenents/MainRecepies.js
  src/compenents/MainRecipes.js
  src/compenents/MealCards.js
  src/compenents/RecipeCard.js
  src/compenents/SearchBar.js
  src/contexts/ProvidersManager.js
  src/contexts/RecipesContext.js
  src/contexts/RecipesProvider.js
  src/contexts/SeachbarProvider.js
  src/index.js
  src/pages/MainRecipesPage.js
  src/services/checkPath.js
  src/services/fetchApi.js
  src/styles/MealAndDrinkCards.css
  src/styles/SearchBar.css
  src/tests/Footer.spec.js
  src/tests/SearchBar.test.js
Labels: Group-14, code-review

#579 [Grupo 14] Feat: component Switcher
  src/App.js
  src/compenents/Footer.js
  src/compenents/MainRecipes.js
  src/compenents/Switcher.js
  src/contexts/ProvidersManager.js
  src/index.js
Labels: Group-14, code-review

#567 [Group 25] Requisitos 70 e 71
  src/pages/ExplorerDrinks/data.js
  src/pages/ExplorerDrinks/index.jsx
  src/pages/ExplorerFoods/data.js
  src/pages/ExplorerFoods/index.jsx
Labels: Group 25, code-review

#566 [ Group 19 ] Searchbar
  src/App.css
  src/components/Header.js
  src/components/SearchBarFilters.js
  src/context/Provider.js
  src/pages/recipes/Drinks.js
  src/pages/recipes/Foods.js
  src/services/getDrinks.js
  src/services/getMeals.js
Labels: group-19

#551 [Group 1]Feat: tela de explorar por origem area - requisitos 78, 79 e 81
  src/Pages/Explore/ExploreFoods/ExploreArea.jsx
  src/Pages/index.js
  src/components/Routes.jsx
  src/services/Data.jsx
  src/store/Provider.jsx
Labels: Group 1

#594 [Group 1]Feat: requisito 35, 39, 40
  src/Pages/Drinks/DrinkId.jsx
  src/Pages/Drinks/DrinkInProgress.jsx
  src/Pages/Foods/FoodId.jsx
  src/Pages/Foods/FoodInProgress.jsx
  src/Pages/Profile/Login.jsx
  src/store/Provider.jsx
Labels: Group 1

#607 [Group 25] Requisito 72
  src/pages/ExplorerDrinks/index.jsx
  src/pages/ExplorerFoods/index.jsx
Labels: Group 25

#609 [Group 25] Requisito 73
  src/pages/ExplorerFoods/index.jsx
Labels: Group 25

#559 Main group 19 - Explore Page
  src/App.css
  src/pages/explore/DrinkExplore.js
  src/pages/explore/ExplorePage.js
  src/pages/explore/FoodsExplore.js
Labels: group-19

#569 [Group 15] - Favorite Recipe
  src/components/ButtonFiltersRecipe.jsx
  src/components/RecipeFavoriteCard.jsx
  src/hooks/useExploreRecipe.js
  src/hooks/useFavoriteRecipe.js
  src/hooks/useRecipeDetails.js
  src/hooks/useRecipeFilter.js
  src/hooks/useRecipeProgress.js
  src/pages/DrinkDetails.jsx
  src/pages/DrinkExplore.jsx
  src/pages/Explore.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/FoodDetails.jsx
  src/pages/FoodExplore.jsx
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/pages/RecipesDone.jsx
  src/services/data.js
  src/store/RecipeContext.jsx
Labels: Group-15, inDevelopement

#487 [Grupo 16] - Tela de detalhes da receita - continuação
  package-lock.json
  package.json
  src/App.js
  src/components/Card/Card.jsx
  src/components/Card/styles.js
  src/components/CardList/CardGrid.jsx
  src/components/CardList/CardList.jsx
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/CarouselCard.jsx
  src/components/Carousel/styles.js
  src/components/MealVideo/MealVideo.jsx
  src/components/RecipeInfo/RecipeInfo.jsx
  src/components/RecipeIngredients/RecipeIngredients.jsx
  src/components/RecipeInstructions/RecipeInstructions.jsx
  src/components/SearchBar/SearchBar.jsx
  src/context/DetailsContext.jsx
  src/context/FilteredRecipesContext.jsx
  src/helpers/carouselData.js
  src/helpers/localStorageHelper.js
  src/hooks/useDetailsProvider.js
  src/pages/DoneRecipes.jsx
  src/pages/ExploreArea.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/Home.jsx
  src/pages/RecipeDetails.jsx
  src/services/formatingService.js
  src/styles/recipeDetails.js
Labels: code-review

#463 [Group 25] - Detalhes Receita
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/components/Footer/index.jsx
  src/components/Header/index.jsx
  src/components/SearchButton/index.jsx
  src/components/shared/button/index.jsx
  src/pages/Drink/index.jsx
  src/pages/Drinks/index.jsx
  src/pages/Explorer/index.jsx
  src/pages/Food/index.jsx
  src/pages/Perfil/index.jsx
  src/service/recipesApi.js
  src/styles/global.css
Labels: Group 25, inDevelopement

#622 [Group 1] Fix: Arrumando conflitos, passando 41.
  src/App.css
  src/Pages/Drinks/DrinkId.jsx
  src/Pages/Drinks/DrinkInProgress.jsx
  src/Pages/Foods/FoodId.jsx
  src/Pages/Foods/FoodInProgress.jsx
  src/Pages/InProgress/DrinkInProgress.jsx
  src/Pages/InProgress/FoodInProgress.jsx
  src/Pages/index.js
  src/components/Routes.jsx
  src/services/Data.jsx
Labels: Group 1

#640 [GROUP 18] Feat: req82-87
  src/Pages/Profile/Profile.css
  src/Pages/Profile/index.jsx
Labels: code-review

#649 [Main group 15] - Explore screens
  README.md
  src/components/RecipeCard.jsx
  src/components/RecipeIngredientCard.jsx
  src/hooks/useIngredients.js
  src/hooks/useMainRecipe.js
  src/pages/DrinkIngredientExplore.jsx
  src/pages/FoodArea.jsx
  src/pages/FoodIngredientExplore.jsx
  src/pages/Foods.jsx
  src/pages/NotFound.jsx
  src/routes/Routes.jsx
  src/services/data.js
  src/store/RecipeContext.jsx
Labels: Group-15

#652 [Group 25] Requisito 78
  src/pages/ExplorerFoodsLocal/index.jsx
Labels: Group 25

#581 [Group 7 ] Tela de perfil - req e testes
  src/components/ButtonsProfile.jsx
  src/components/Header.jsx
  src/pages/Profile.jsx
  src/tests/Header.test.js
  src/tests/Profile.test.js
Labels: Group 7

#547 [grupo -3 ] searchBar not complete
  src/components/Header.js
  src/components/SearchBarForm copy.js
  src/components/SearchBarForm.js
  src/pages/Bebidas.js
  src/services/fetchApiSearchBar.js
Labels: code-review

#632 [ Main group 4 ] explore food or drinks randomly
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarComidas.js
Labels: Group 4, code-review

#666 [grupo-3] search bar not complete
  src/components/Card copy.jsx
  src/components/Categorias.jsx
  src/components/SearchBarForm.js
  src/pages/Bebidas.js
  src/services/fetchApiSearchBar.js
Labels: code-review

#677 [Grupo 14] merge profile
  src/compenents/SearchBarHeader.js
  src/contexts/RecipesAppContext.js
  src/pages/Perfil.js
  src/pages/Profile.js
  src/styles/Profile.css
Labels: Group-14, code-review

#617 [Grupo 14] Providers Manager
  src/App.js
  src/contexts/ProvidersManager.js
  src/index.js
Labels: Group-14, code-review

#220 [Grupo 14] Tela receitas feitas
  package.json
  src/compenents/CardDrinkDoneFav.js
  src/compenents/CardMealDoneFav.js
  src/compenents/Switcher.js
  src/pages/DoneRecepies.js
  src/pages/ReceitasFeitas.js
Labels: Group-14

#686 [Grupo 4] feat: req 54 to 59
  src/components/DoneRecipes/Category.js
  src/components/DoneRecipes/DoneDate.js
  src/components/DoneRecipes/DoneRecipeCard.js
  src/components/DoneRecipes/DoneRecipesImports.js
  src/components/DoneRecipes/Image.js
  src/components/DoneRecipes/Share.js
  src/components/DoneRecipes/Tag.js
  src/components/DoneRecipes/Title.js
  src/pages/ReceitasFeitas.js
Labels: Group 4, code-review

#667 [Group 1] Feat: requisito 37, 43, 44
  src/Pages/Drinks/DrinkId.jsx
  src/Pages/Foods/FoodId.jsx
  src/Styles/Recomendation.css
Labels: Group 1

#643 [Grupo 16] Tela de explorar por local de origem/area
  src/App.js
  src/components/AreasList/AreasList.jsx
  src/pages/ExploreArea.jsx
Labels: code-review

#656 :sparkles: ExploreByArea Screen
  src/App.js
  src/components/Cards.js
  src/pages/ExploreFoodArea.jsx
  src/pages/NotFound.jsx
Labels: code-review

#721 [grupo -3] requirements searchBar complete
  src/components/Card copy.jsx
  src/components/Card.jsx
  src/components/SearchBarForm copy.js
  src/components/SearchBarForm.js
  src/components/search bar/SearchBarForm.js
Labels: code-review

#446 [GRUPO 21] (Tela Explorar) Adiciona a tela de explorar com 2 links para explorar comidas e bebidas.
  src/App.js
  src/pages/Explore/index.jsx
  src/pages/Explore/styles.module.scss
  src/tests/Explore.test.js
  src/tests/helpers/renderWithRoute.js
Labels: code-review

#166 [GRUPO 21] (Tela principal de receitas) Renderiza todos os card com as informações vindas da Api.
  src/App.js
  src/components/Carousel/index.jsx
  src/components/Carousel/styles.module.scss
  src/components/Header/index.jsx
  src/components/Header/styles.module.scss
  src/components/RecipesCardsGrid/components/RecipeSimpleCard/index.jsx
  src/components/RecipesCardsGrid/components/RecipeSimpleCard/styles.module.scss
  src/components/RecipesCardsGrid/index.jsx
  src/components/RecipesCardsGrid/styles.module.scss
  src/context/Recipes.jsx
  src/global.scss
  src/images/plus18.svg
  src/index.js
  src/lib/fetchJson.js
  src/pages/MainRecipes/components/Categories/index.jsx
  src/pages/MainRecipes/components/Categories/styles.module.scss
  src/pages/MainRecipes/index.jsx
  src/pages/MainRecipes/styles.module.scss
  src/pages/Receitas/index.jsx
  src/services/drinksData.js
  src/services/mealsData.js
  src/services/recipesData.js
  yarn.lock
Labels: code-review

#724 [Group 1] Feat: requisitos 45, 46
  src/Pages/Drinks/DrinkId.jsx
  src/Pages/Foods/FoodId.jsx
  src/Styles/Recomendation.css
Labels: Group 1

#761 [Group 11][Favorite Recipes Page]
  src/components/FavoriteCardDrink.jsx
  src/components/FavoriteCardMeal.jsx
  src/components/FavoriteCards.jsx
  src/components/ShareButton.jsx
  src/context/FavoritesContext.js
  src/context/FavoritesProvider.js
  src/context/UserProvider.js
  src/effects/RecipeShared.js
  src/effects/RemoveFavorite.js
  src/pages/DrinkDetails.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/FoodDetails.jsx
  src/services/GetFavoritesDetails.js
Labels: code-review

#755 [Main group 22] Favorite Recipes Page
  src/components/Header.jsx
  src/components/RecipeDetailsHeader.jsx
  src/hooks/useLocalStorage.js
  src/images/drinkIcon.svg
  src/images/exploreIcon.svg
  src/images/mealIcon.svg
  src/pages/FavoriteRecipes.jsx
  src/styles/searchBar.css
Labels: Group-22

#775 [Group 11] [Profile Screen]
  src/effects/RecipeDone.js
  src/pages/Profile.jsx
  src/services/GetDoneDetails.js
Labels: code-review

#683 [ Group 4] Arrumando o comportamento da função de gerar array de ingredientes
  src/utils/index.js
Labels: Group 4, code-review

#539 [Grupo 4] Página de favoritos
  src/App.js
  src/components/Favorite.js
  src/components/Favorite/Category.js
  src/components/Favorite/Drink.js
  src/components/Favorite/Image.js
  src/components/Favorite/Meal.js
  src/components/Favorite/Share.js
  src/components/Favorite/Title.js
  src/components/FavoriteCard.js
  src/components/Header.js
  src/components/Recipe/Carousel.js
  src/components/Recipe/FavoriteMeal.js
  src/components/Recipe/Recomendations.js
  src/context/StorageContext.js
  src/context/StorageProvider.js
  src/context/index.js
  src/pages/BebidasDetalhes.js
  src/pages/ComidasDetalhes.js
  src/pages/ReceitasFavoritas.js
Labels: Group 4, code-review

#736 [grupo 4] receitas em processo
  src/App.js
  src/css/ComidasEmProcessoCSS.css
  src/pages/BebidasEmProcesso.js
  src/pages/ComidasEmProcesso.js
Labels: Group 4, code-review

#779 [group-31] Explorer page drinks foods
  src/App.js
  src/components/buttonExplore/index.js
  src/pages/Explore/index.js
  src/pages/ExploreByAreaFoods/index.js
  src/pages/ExploreByIngredientDrinks/index.js
  src/pages/ExploreByIngredientFoods/index.js
  src/pages/ExploreDrinks/ExploreDrinks.css
  src/pages/ExploreDrinks/index.js
  src/pages/ExploreFoods/ExploreFoods.css
  src/pages/ExploreFoods/index.js
  src/services/fetchApiMain.js
Labels: code-review

#654 [Group 25] Explorer Origin
  src/App.jsx
  src/pages/Explorer/index.jsx
  src/pages/ExplorerDrinks/data.js
  src/pages/ExplorerDrinks/index.jsx
  src/pages/ExplorerFoods/data.js
  src/pages/ExplorerFoods/index.jsx
  src/pages/ExplorerFoodsLocal/index.jsx
  src/pages/NotFound/index.jsx
  src/service/recipesApi.js
Labels: Group 25, inDevelopement

#795 [Group 25] - Repairs
  src/components/CardRecipe/index.jsx
  src/components/ItemCard/index.jsx
  src/components/SearchBar/index.jsx
  src/context/recipesContext/recipesProvider.js
  src/pages/Drinks/index.jsx
  src/pages/ExplorerDrinksIngredients/index.jsx
  src/pages/ExplorerFoodsIngredients/index.jsx
  src/pages/Foods/index.jsx
Labels: Group 25, code-review

#814 [main-group-22 ] - done-recipes
  src/components/RecipeDetailsHeader.jsx
  src/contexts/RecipesProvider.jsx
  src/hooks/useLocalStorage.js
  src/pages/DoneRecipes.jsx
  src/styles/DoneRecipes.css
Labels: Group-22

#807 [Grupo 4] Arrumando bugs nos req: 10, 11, 16, 21, e 28
  src/components/DrinksCards.js
  src/components/MealsCards.js
  src/pages/Perfil.js
Labels: Group 4, code-review

#461 [Grupo 14] Explore ingredients pages
  package-lock.json
  package.json
  src/compenents/Header.js
  src/compenents/MainRecipes.js
  src/compenents/MealCards.js
  src/contexts/HeaderContext.js
  src/contexts/HeaderProvider.js
  src/contexts/RecipesProvider.js
  src/pages/DoneRecepies.js
  src/pages/Drinks.js
  src/pages/DrinksIngredients.js
  src/pages/Explore.js
  src/pages/Foods.js
  src/pages/FoodsArea.js
  src/pages/FoodsIngredients.js
  src/pages/MainRecipesPage.js
  src/pages/Profile.js
  src/pages/ProfilePage.js
  src/pages/ReceitasFavoritas.js
  src/tests/FoodsIngredients.test.js
Labels: Group-14

#556 [Grupo 14 ] Merge explore ingredients
  src/pages/Bebidas.js
  src/pages/Comidas.js
Labels: Group-14

#629 [Grupo 14] Pagina receitas favoritas
  src/compenents/FavoriteBtn.js
  src/compenents/SearchBar.js
  src/compenents/Switcher.js
  src/contexts/RecipesProvider.js
  src/pages/FavoriteRecipes.js
Labels: Group-14

#780 [Group 9] - Requisito 47-53
  src/context/RecipesProvider.js
  src/pages/RecipesDrinksInProgress.js
  src/pages/RecipesFoodsInProgress.js
  src/services/api.js
  src/utils/checkFavoritesInLocalStorage.js
  src/utils/checkIngredients.js
  src/utils/mapDrinkIngredients.js
  src/utils/verifyIngredientsInLocalStorage.js
Labels: code-review

#793 [GRUPO 21] (Receitas/Global) Componente de busca que permite encontrar receitas
  src/components/Header/components/Search/index.jsx
  src/components/Header/components/Search/styles.module.scss
  src/components/Header/index.jsx
  src/components/Header/styles.module.scss
  src/context/Recipes.jsx
  src/pages/MainRecipes/components/Categories/index.jsx
  src/services/drinksData.js
  src/services/mealsData.js
  src/services/recipesData.js
Labels: code-review

#819 [Grupo 4] Página de explorar por local de origem
  src/components/MealsAreasDropdown.js
  src/components/MealsCategoryButtons.js
  src/pages/ExplorarComidasArea.js
  src/pages/PaginaNaoEncontrada.js
  src/redux/actions/loadingAction.js
  src/redux/actions/mealsAction.js
  src/redux/reducers/loadingReducer.js
  src/redux/reducers/mealsReducer.js
  src/services/meals.js
Labels: Group 4, code-review

#874 [Group 9] - Requisito 51
  src/context/RecipesProvider.js
  src/pages/RecipesDrinksInProgress.js
  src/pages/RecipesFoodsInProgress.js
  src/utils/mapDrinkIngredients.js
  src/utils/mapIngredients.js
  src/utils/verifyIngredientsInLocalStorage.js
Labels: code-review

#882 [GROUP 18] feat:req75-81
  src/Components/ExploreDrink/index.jsx
  src/Components/MealsCard/index.jsx
  src/Pages/ExploreArea/index.jsx
  src/Pages/ExploreIngredients/index.jsx
  src/Pages/ExploreIngredientsDrink/index.jsx
  src/Pages/ExploreIngredientsMeal/index.jsx
  src/Pages/NotFound/index.jsx
  src/Pages/RecipeMainPage/index.jsx
  src/Router.jsx
  src/context/RecipesProvider.js
  src/services/fetchRecipes.js
Labels: code-review

#542 [GROUP 3] - tela progresso
  public/icons8-comida-50.png
  public/icons8-food-48.png
  public/index.html
  src/App.css
  src/App.js
  src/components/EmProgesso.jsx
  src/components/EmProgressPage/Ingredientes.jsx
  src/components/FavoriteFood.jsx
  src/components/Header.js
  src/components/ReceitaBebidaDetalhe.js
  src/components/ReceitaComidaDetalhe.js
  src/components/arquivos copy/FavoriteFood.jsx
  src/components/arquivos copy/IngredientesCopy.jsx
  src/pages/Bebidas.js
  src/pages/BebidasAtiva.js
  src/pages/Comidas.js
  src/pages/ComidasAtiva.js
  src/pages/Perfil.js
  src/styles/perfil.js
Labels: inDevelopement

#881 [ Main group 4 ] explore ingredients - renders ingredients
  src/components/DrinkIngredientCard.js
  src/components/DrinksCategoryButtons.js
  src/components/IngredientCard.js
  src/components/MealsCategoryButtons.js
  src/pages/ExplorarBebidasIngredientes.js
  src/pages/ExplorarComidasIngredientes.js
  src/redux/actions/drinksAction.js
  src/redux/actions/loadingAction.js
  src/redux/actions/mealsAction.js
  src/redux/reducers/drinksReducer.js
  src/redux/reducers/loadingReducer.js
  src/redux/reducers/mealsReducer.js
  src/services/drinks.js
  src/services/meals.js
Labels: Group 4, code-review

#928 Main group 26 lucaspedroso
  src/App.js
  src/components/Cards.js
  src/components/FilterButtons.js
  src/components/Header.js
  src/components/Search.js
  src/index.css
  src/pages/Comidas.js
  src/pages/Explorar.js
  src/pages/FavoriteRecipies.js
  src/pages/NotFound.js
  src/pages/drinks/Drinks.js
  src/pages/explore/DrinkIngredients.js
  src/pages/explore/ExploreDrink.js
  src/pages/explore/ExploreFood.js
  src/pages/explore/FoodArea.js
  src/pages/explore/FoodIngredients.js
  src/pages/foods/FoodDetails.js
  src/pages/foods/Foods.js
  src/services/functions.js
  src/services/index.js
  src/styles/DetailsPages.module.scss
  src/styles/Header.module.scss
  src/styles/MainPages.module.scss
Labels: code-review

#868 [Group 1] Fix: requisito 87
  src/Pages/Drinks/DrinkId.jsx
  src/Pages/Foods/FoodId.jsx
  src/Pages/Foods/Foods.jsx
  src/Pages/InProgress/DrinkInProgress.jsx
  src/Pages/InProgress/FoodInProgress.jsx
  src/Pages/Profile/Login.jsx
  src/Pages/Profile/Profile.jsx
  src/store/Provider.jsx
Labels: Group 1

#799 [GRUPO 21] (Tela Explorar comidas ou bebidas) Adiciona a telas com links para explorar.
  src/App.js
  src/pages/Explore/components/ExploreButtons/index.jsx
  src/pages/Explore/index.jsx
  src/pages/Explore/styles.module.scss
  src/services/drinksData.js
  src/services/mealsData.js
  src/services/recipesData.js
  yarn.lock
Labels: code-review

#905 [GROUP 18] Feat:75-81-CSS
  src/Components/MealsCard/index.jsx
  src/Components/MealsCard/styles.css
  src/Pages/ExploreIngredientsDrink/index.jsx
  src/Pages/ExploreIngredientsDrink/styles.css
  src/Pages/ExploreIngredientsMeal/index.jsx
  src/Pages/ExploreIngredientsMeal/styles.css
Labels: enhancement

#897 [Grupo 3] - details recipe fixes
  package-lock.json
  package.json
  src/components/Categorias.jsx
  src/components/EmProgressPage/Ingredientes.jsx
  src/components/ReceitaBebidaDetalhe.js
  src/components/ReceitaComidaDetalhe.js
  src/components/RecomendacoesCard.js
  src/components/arquivos copy/FavoriteFood.jsx
  src/components/arquivos copy/IngredientesCopy.jsx
  src/components/searchBar.css
  src/index.js
  src/styles/DetalhesPagina.css
  src/styles/RecomendacoesCard.css
  src/styles/custom.scss
Labels: code-review

#915 Group 19 explore pages
  src/App.css
  src/Routes.js
  src/components/IngredientList.jsx
  src/context/Provider.js
  src/pages/explore/ExploreFoodByArea.js
  src/pages/explore/ingredients/DrinksIngredients.js
  src/pages/explore/ingredients/FoodIngredients.js
  src/pages/otherPages/NotFound.js
  src/pages/recipes/Drinks.js
  src/pages/recipes/Foods.js
  src/services/getFoodByArea.js
  src/services/getIngredients.js
  src/services/getMeals.js
Labels: group-19

#850 [Group 26] Recipe In Progress
  package-lock.json
  src/pages/drinks/DrinkDetails.js
  src/pages/drinks/DrinkProgress.js
  src/pages/foods/FoodDetails.js
  src/pages/foods/FoodProgress.js
  src/services/functions.js
  src/styles/DetailsPages.module.scss
Labels: code-review

#949 [GRUPO 21] (Explorar origem) Renderiza todas as receitas e filtra por origem.
  src/App.js
  src/components/Header/components/Search/index.jsx
  src/components/Header/index.jsx
  src/components/RecipesCardsGrid/components/RecipeSimpleCard/index.jsx
  src/context/Recipes.jsx
  src/pages/Explore/components/Dropdown/index.jsx
  src/pages/Explore/components/ExploreCards/index.jsx
  src/pages/Explore/components/ExploreCards/styles.module.scss
  src/pages/Explore/index.jsx
  src/pages/Explore/styles.module.scss
  src/pages/MainRecipes/index.jsx
  src/pages/Recipe/components/Recommendations/index.jsx
  src/pages/Recipe/components/Video/index.jsx
  src/services/drinksData.js
  src/services/mealsData.js
Labels: code-review

#841 [ Group19 ] Detail Screen
  cypress/integration/recipe_detail_spec.js
  src/Routes.js
  src/components/DrinkShareAndFavorite.js
  src/components/MealShareAndFavorite.js
  src/components/RecipesList.jsx
  src/components/StartRecipeButton.js
  src/components/inProgress/InProgressDrink.js
  src/components/inProgress/InProgressMeal.js
  src/components/inProgress/RecipesInProgress.js
  src/context/Provider.js
  src/index.js
  src/pages/Profile/Profile.css
  src/pages/Profile/Profile.js
  src/pages/otherPages/Login.js
  src/pages/recipes/DrinksDetails.js
  src/pages/recipes/MealDetails.js
  src/pages/recipes/in-progress/drinksProgress.js
  src/pages/recipes/in-progress/mealsProgress.js
  src/pages/recipes/recipeDetails.css
  src/services/getDrinks.js
  src/services/getMeals.js
Labels: group-19

#974 [GROUP 3] - Loading feats
  src/components/Card.jsx
  src/components/Categorias.jsx
  src/components/EmProgesso.jsx
  src/components/EmProgressPage/Ingredientes.jsx
  src/components/FavoriteFood.jsx
  src/components/Loading.jsx
  src/components/SearchBarForm.js
  src/pages/Bebidas.js
  src/pages/BebidasAtiva.js
  src/pages/Comidas.js
  src/pages/ComidasAtiva.js
  src/pages/DetalhesBebida.js
  src/pages/DetalhesComida.js
  src/pages/ExplorarBebidasING.js
  src/pages/ExplorarComidasArea.js
  src/pages/ExplorarComidasING.js
Labels: inDevelopement

#977 [Grupo 1] Receitas favoritas
  public/favicon.ico
  public/index.html
  src/Pages/Profile/FavoriteRecipes.jsx
  src/components/RecipeItem.jsx
  src/components/RecipeList.jsx
  src/store/Provider.jsx
Labels: Group 1

#958 [GRUPO 21] (Receitas Feitas) Renderiza todos os cards de todas as receitas feitas
  src/App.js
  src/components/HorizontalRecipeCard/index.jsx
  src/components/HorizontalRecipeCard/styles.module.scss
  src/pages/DoneRecipes/index.jsx
  src/pages/DoneRecipes/styles.module.scss
  src/pages/Explore/index.jsx
Labels: code-review

#976 [Grupo 9] - Requisitos 82-87
  src/pages/Profile.js
  src/pages/profile.css
Labels: code-review

#1000 [Grupo 9] - Fix app bugs
  src/components/DisfavorButton.js
  src/context/RecipesProvider.js
  src/pages/DoneRecipes.js
  src/pages/FavoriteRecipes.js
  src/pages/RecipesDrinksDetails.js
  src/pages/RecipesDrinksInProgress.js
  src/pages/RecipesFoodsDetails.js
  src/pages/RecipesFoodsInProgress.js
  src/utils/prepareDoneRecipesObject.js
Labels: code-review

#992 [GROUP 3] - new Loading
  src/components/Loading.jsx
  src/images/loginIcon.png
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/ExplorarBebidasING.js
  src/pages/ExplorarComidasING.js
  src/pages/Login.js
  src/styles/Header.css
  src/styles/Login.css
Labels: inDevelopement

#1035 [Grupo 4] Carousel usando react-multi-carousel
  package-lock.json
  package.json
  src/App.js
  src/components/Recipe/Carousel.js
  src/components/Recipe/CarouselCard.js
  src/styles/carousel.css
  src/styles/carouselCard.css
  src/styles/recipe.css
Labels: Group 4, bug, enhancement, inDevelopement

#1025 [Grupo 4] Implementado estilo da pagina explorar ingredientes...
  .stylelintignore
  .stylelintrc.json
  package-lock.json
  package.json
  src/App.js
  src/components/DrinkIngredientCard.js
  src/components/Footer.js
  src/components/IngredientCard.js
  src/components/Recipe/FavoriteDrink.js
  src/components/Recipe/FavoriteMeal.js
  src/css/App.css
  src/css/_login.scss
  src/css/_pagExplorarPorIngredientes.scss
  src/css/_pagProcesso.scss
  src/css/_search.scss
  src/css/_utils.scss
  src/css/footer.module.css
  src/css/index.css
  src/css/style.css
  src/css/style.css.map
  src/css/style.scss
  src/index.js
  src/pages/ComidasEmProcesso.js
Labels: Group 4, enhancement
